[package]
name = "simple-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
bytes = "1.7.1"
dashmap = "6.1.0"
enum_dispatch = "0.3.13"
lazy_static = "1.5.0"
thiserror = "1.0.63"
